# Generated by Django 3.2.6 on 2021-08-16 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='task',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='task',
            name='last_modified',
        ),
    ]
